config/routes.rb
Rails.application.routes.draw do
  root 'time_cards#show'  

  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/timecard', to: 'time_cards#show'
  post '/timecard', to: 'time_cards#create'
  get '/monthly', to: 'time_cards#index'

  resources :users, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/time_card.rb
class TimeCard < ApplicationRecord
  belongs_to :user

  validates :year, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :month, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :day, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validate :valid_date # このバリデーションは year, month, day のバリーデーションの下に定義しないと有効でない
  validates :in_at, presence: true, if: lambda { |m| !m.out_at.nil? }
  validate :out_at_is_later_than_in_at

  class << self
    # 今日のタイムカードを取得する
    def today(user)
      date = Date.today
      condition = { user: user, year: date.year, month: date.month, day: date.day }
      self.find_by(condition) || self.new(condition)
    end

    # 指定年月のタイムカードを取得する
    def monthly(user, year, month)
      self.where(user: user, year: year, month: month).order(:day).all
    end
  end

  # 勤務状況を取得する
  def working_status
    case [!!in_at, !!out_at]
    when [false, false]
      :not_arrived # 未出勤
    when [true, false]
      :working # 勤務中
    when [true, true]
      :left # 退勤済
    end
  end

  # タイムカードの日付を返す
  def date
    Date.new(year, month, day)
  end

  # 勤務時間を返す（単位は秒）
  def work_hours_in_seconds
    if in_at && out_at
      out_at - in_at
    else
      0
    end
  end

  private

    # カスタムバリデーション（正しい日付か？）
    def valid_date
      return if errors[:year].any? || errors[:month].any? || errors[:day].any?
      
      if !Date.valid_date?(year, month, day)
        errors[:base] << '不正な日付です'
      end
    end

    # カスタムバリデーション（退勤時間が出勤時間より後か？）
    def out_at_is_later_than_in_at
      return if in_at.nil? || out_at.nil?

      if in_at > out_at
        errors[:base] << '退勤時間は、出勤時間より後の時間である必要があります'
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :time_cards, dependent: :destroy
  
  before_save :downcase_email
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  class << self
    # 渡された文字列のハッシュ値を返す
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
  end

  private

    # メールアドレスをすべて小文字にする
    def downcase_email
      self.email.downcase!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
  
    private
    
        # ユーザーのログインを確認する
        def logged_in_user
          unless logged_in?
            store_location
            flash[:danger] = "ログインしてください。"
            redirect_to login_url
          end
        end  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_back_or root_url
    else
      flash.now[:danger] = 'メールアドレスまたはパスワードが違います。'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to login_url
  end
end

app/controllers/time_cards_controller.rb
class TimeCardsController < ApplicationController
  before_action :logged_in_user

  def index
    today = Date.today
    @year = today.year
    @month = today.month
    @time_cards = monthly_time_cards(current_user, @year, @month)
  end

  def show
    @time_card = TimeCard.today(current_user)
  end

  def create
    @time_card = TimeCard.today(current_user)
    
    if params[:in]
      @time_card.in_at = Time.now
    elsif params[:out]
      @time_card.out_at = Time.now
    end

    if @time_card.save
      render json: { status: 'success', time_card: @time_card, working_status: @time_card.working_status }
    else
      render json: { status: 'error' }
    end
  end

  private

    # 指定年月の全ての日のタイムカードの配列を取得する（タイムカードが存在しない日はnil）
    def monthly_time_cards(user, year, month)
      number_of_days_in_month = Date.new(year, month, 1).next_month.prev_day.day
      results = Array.new(number_of_days_in_month) # 月の日数分nilで埋めた配列を用意
      time_cards = TimeCard.monthly(user, year, month)
      time_cards.each do |card|
        results[card.day - 1] = card
      end
      results
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to root_url
    else
      render 'new'
    end
  end

  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                    :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # ログイン済みのユーザーを返す
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    end
  end

  # 渡されたユーザーがログイン済みユーザーであればtrueを返す
  def current_user?(user)
    user == current_user
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # 記憶したURL (もしくはデフォルト値) にリダイレクト
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # アクセスしようとしたURLを覚えておく
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/time_cards_helper.rb
module TimeCardsHelper
  # 日付の日本語表現を取得する
  def date_in_japanese(date = Date.today, format = :full)
    case format
    when :full
      "#{date.year}年#{date.month}月#{date.day}日 #{day_of_the_week_in_japanese(date)}"
    when :month_day
      "#{date.month}月#{date.day}日"
    end
  end

  # 曜日の日本語表現を取得する
  def day_of_the_week_in_japanese(date, format = :full)
    result =
      case date.wday
      when 0
        '日曜日'
      when 1
        '月曜日'
      when 2
        '火曜日'
      when 3
        '水曜日'
      when 4
        '木曜日'
      when 5
        '金曜日'
      when 6
        '土曜日'
      end

    format == :short ? result[0] : result
  end

  # 勤務状況を取得する
  def working_status(time_card)
    case time_card.working_status
    when :not_arrived
      '未出勤'
    when :working
      '勤務中'
    when :left
      '退勤済'
    end  
  end

  # 指定した年月の1日から月末までの日付とインデックスを引数としてブロックを実行する
  def each_date_in_month(year, month)
    date = Date.new(year, month, 1)

    while date.month == month do
      yield date, date.day - 1
      date = date.next_day
    end
  end

  # 00:00 形式の時間を返す
  def time_str(time)
    time ? time.strftime('%H:%M') : ''
  end

  # 00:00 形式の勤務時間を返す
  def time_diff_str(second)
    hours, rest = second.divmod(60 * 60)
    minutes, rest = rest.divmod(60)

    '%02d' % hours + ':' '%02d' % minutes
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title><%= yield(:title) %> - 勤怠管理システム</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary p-2">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">勤怠管理システム</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <% if logged_in? %>
              <li class="nav-item">
                <%= link_to "マイページ", root_path, class: "nav-link active" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", logout_path, method: :delete, class: "nav-link active" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">入力が正しくありません。</div>
    <ul></ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>
        <%= msg %>
      </li>
    <% end %>
  </div>
<% end %>

app/views/time_cards/index.html.erb
<% provide(:title, "勤務表") %>
<h1><%= @year %>年<%= @month %>月の勤務表</h1>
<table class="table table-bordered">
  <thead class="table-light">
    <tr>
      <th>日付</th>
      <th>曜日</th>
      <th>出勤時間</th>
      <th>退勤時間</th>
      <th>勤務時間</th>
    </tr>
  </thead>
  <% each_date_in_month(@year, @month) do |date, index| %>
    <tbody>
      <tr>
        <td>
          <%= date_in_japanese(date, :month_day) %>
        </td>
        <td>
          <%= day_of_the_week_in_japanese(date, :short) %>
        </td>
      <% if @time_cards[index] %>
        <td>
          <%= time_str(@time_cards[index].in_at) %>
        </td>
        <td>
          <%= time_str(@time_cards[index].out_at) %>
        </td>
        <td>
          <%= time_diff_str(@time_cards[index].work_hours_in_seconds) %>
        </td>
      <% else %>
        <td></td>
        <td></td>
        <td></td>
      <% end %>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/time_cards/show.html.erb
<% provide(:title, "マイページ") %>
<h1>マイページ</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <p>こんにちは、 <%= current_user.name %> さん</p>
    <p>今日は <%= date_in_japanese %> です。</p>
    <p>
      現在ステータス：
      <span id="work-status">
        <%= working_status(@time_card) %>
      </span>
    </p>
    <%= form_tag('/timecard', remote: true, id: 'timecard-form') do |f| %>
      <div class="submit_form">
      <%= button_tag('出勤', name: 'in', id: 'in', class: 'btn btn-outline-primary btn-lg', disabled: !!@time_card.in_at) %>
      <%= button_tag('退勤', name: 'out', id: 'out', class: 'btn btn-outline-primary btn-lg', disabled: !@time_card.in_at || !!@time_card.out_at) %>
      </div>
    <% end %>
    <div>
      <%= button_to '勤務表を確認する', monthly_path, method: :get, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :name, '氏名' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email, 'メールアドレス' %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワード（確認用）' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <%= f.submit yield(:button_text), class: 'btn btn-primary form-control' %>
<% end %>

app/views/users/new.html.erb
<% provide(:title, "アカウント登録") %>
<% provide(:button_text, '登録') %>
<h1>アカウント登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>